### PR TITLE
Add new patches, hide in-game CRT filter settings in no-crt

### PR DESCRIPTION
**Pull request by SBence**
- Modified **no-crt** patch to hide in-game settings for the CRT filter
- Added patches
  - **no-beta-langs**: Set `beta = nil` on all languages to make them selectable
    - Added to default patches
  - **max-volume**: Set master volume to 100 by default

### CODE REVIEW

**Comment by SBence** [comment]
Should I add **max-volume** to default patches as well?
The reason I made that patch in the first place is that, in my experience, the volume on mobile devices is usually adjusted at the system level, as opposed to being done so at the application level. The game's default volume setting of 50 in this case makes it noticeably quieter compared to other applications, requiring manual adjustment by the user to either the system media volume or the game's volume.

**Comment by ronald-jaepel** [comment]
What does the volume patch do exactly? Does it set it to 100 once on first start or does it set it to 100 on every start?

If it's the latter, I personally would not include it in the defaults. I constantly switch volume levels. If I listen to music, I turn down the in-game music but max out game sounds; if I listen to a podcast, the game sounds go down to ~20%; if I just play the game I bring up game sounds and music, etc.

**Comment by SBence** [comment]
It only overwrites the default master volume level. If the user changes it, it's saved as usual.

**Comment by ronald-jaepel** [comment]
In that case I wouldn't mind it. Thanks for the addition and clarification.

**Comment by antipatico** [comment]
Great PR, thanks for the contribution. Have you tested this new patches on older supported versions of the game? @SBence 

On regards to the default patches, I am okay to add both to the list.

I will test on my device, apply some minor changes and merge soon. Thanks again!

**Comment by antipatico** [comment]
I changed the beta-langs feature to fix the functionality instead of removing it. Now, the beta aesthetic is kept for the button and also the disclaimer showing that the language is in beta. As an user, you need to click the desired beta language twice.

Thanks for the PR, v0.5.0 out soon!

**Comment by SBence** [comment]
Apologies for the late reply.
The patches haven't been tested on older versions of the game as I no longer have access to them. I did, however, manually make those changes in said older versions before, which is why I included them in the list of supported versions.
I see that you've included a much better alternative though, which would've rendered my testing irrelevant anyway.

**Pull request merged**
