### PR TITLE
Adapt 3 patches from the PortMaster tweaks for Baltaro on handheld linux.

### PR DESCRIPTION
**Pull request by rancossack**
Adapt 3 patches from the PortMaster tweaks for Baltaro on handheld linux.

* simple-fx further reduces the special effects
* nunito-font replaces the default font with nunito, a font optimized for small displays
* square-display moves the cards closer to the center and is useful for foldable displays.

Upstream changes:
https://github.com/nkahoang/PortMaster-nkaHoang

### CODE REVIEW

**Comment by antipatico** [comment]
Nice PR, I have to test it before being able to merge it.

That being said, the following talking point arise:
* Is [blake502](https://github.com/blake502/) involved with this patches or you just left it as an author? Are you the original author of the patches?
*  It may be sensible to have binary patches separated / saved on disk directly. Having a binary resource B64 encoded is quite wasteful. Moreover, is it okay to include the font in the repo or does it have any sort of copyright preventing that? Maybe we should add it to the README.
* Version and README should be updated, I will do that (and hopefully remember to push to PyPi) as the last step of the merge process.

**Comment by antipatico** [comment]
The patches seems to work on my Phone.
I have the following question about the [simple-fx patch](https://github.com/rancossack/balatromobile/blob/0b44be7611ebb6b9fbf5181a771853a810aafb27/balatromobile/patches/simple-fx.toml): when I go to the settings and checkout the `bloom` setting, I see it is on `nil` instead of being `off`.

Are you sure this is the correct way of patching? By looking at the code, it looks like so, but the game behaves strangely by disabling the effect but showing `nil` in the settings.

EDIT: the `simple-fx` patch seems broken to me, does not disable shadows and background, even with juts `basic,simple-fx`. Can you please provide the commandline used to build the version you are using on your handheld device? Thanks!

**Comment by rancossack** [comment]
> Are you sure this is the correct way of patching? By looking at the code, it looks like so, but the game behaves strangely by disabling the effect but showing `nil` in the settings.

I am not actually sure -- it's the way nkahoang
 did it here: https://github.com/nkahoang/PortMaster-nkaHoang/blob/main/ports/balatro/Balatro.sh
Checking the code, I believe disabling crt (I have a pixel and have been testing with the crt patch) also removes the effect; this may not be needed or worth including. 


 
> EDIT: the `simple-fx` patch seems broken to me, does not disable shadows and background, even with juts `basic,simple-fx`. Can you please provide the commandline used to build the version you are using on your handheld device? Thanks!

Removing the shadows need to clear storage and cache; I think it only changes the default setting.

My description here was wrong as well; the backgrounds were only disabled behind the menu screen (with the translucent overlay over gameplay).

I split out actually disabling backgrounds as a separate patch and it works for me now -- I've been building/testing like this:
```
source venv2/bin/activate; ./venv2/bin/balatromobile android Balatro.exe --patches basic,landscape-hidpi,crt,simple-fx,square-display,nunito-font,no-background
adb install --user 0 balatro-1.0.0n-FULL.apk
```

**Comment by rancossack** [comment]
>     * Is [blake502](https://github.com/blake502/) involved with this patches or you just left it as an author? Are you the original author of the patches?
Not involved; I copied the earlier attribution. I'll fix it! The patches are based on nkahoang's [PortMaster script](https://github.com/nkahoang/PortMaster-nkaHoang/blob/main/ports/balatro/Balatro.sh).

>     * It may be sensible to have binary patches separated / saved on disk directly. Having a binary resource B64 encoded is quite wasteful. Moreover, is it okay to include the font in the repo or does it have any sort of copyright preventing that? Maybe we should add it to the README.

That's true.  Do you have any suggestions or preferences on how to package it? (In the patches or artifacts folder?) 
[Nunito](https://fonts.google.com/specimen/Nunito/about) is licensed OFL and should be fine to package -- if we're not embedding it it's better to include a license file for it too. (Similar to this: https://github.com/nkahoang/PortMaster-nkaHoang/blob/main/ports/balatro/balatro/LICENSE.Nunito_OFL.txt)

**Review by antipatico — APPROVED** [review]

**Comment by antipatico** [comment]
I tidied up the things a little, pushed to version 0.2.0 and I switched to using `artifacts` for binary patches.
I will merge it now and publish it on PyPi. Thanks for your contribution!

**Pull request merged**
